### ISSUE TITLE
Transparent background makes buttons break

### ISSUE THREAD

**Issue by Banchion007** [ClearVision/ClearVision-v6#178]
### Did You Search Other Issues?

- [x] I have checked other issues

### Does This Bug Show On The Default Theme?

- [ ] I have reproduced this on the default theme

### Describe The Bug

When I set the background overlay to transparent, the buttons (Channels, Usernames, Messages) aren't selectable in their normal boundaries and are only clickable within the pixels of text.
![Screenshot 2023-12-22 200129](https://github.com/ClearVision/ClearVision-v6/assets/126730693/d1993255-8c9f-4f17-aa74-512a293527d6)
I cant get a SS because Win + Shift + S doesn't include the cursor. 

I couldn't get it to do the same on default, and none of my plugins are doing anything

### Reproduction Steps

```bash
1. set background-overlay to 255,255,255,0
2.
3.
...
```

**Comment by BabyBoySnow** [comment]
@import url(https://clearvision.github.io/Addons/transparency.css)
or 
https://github.com/ClearVision/Addons/blob/master/transparency.css

**Comment by NyxIsBad** [comment]
I don't think it has to do with the transparency addon, it's just they want 0 shading. I'll check

**Comment by NyxIsBad** [comment]
I just replicated your conditions but can't replicate any bugs. My vars are set to 
```css
	--background-shading: 0%; 
	--background-overlay: rgba(255, 255, 255, 0); 
        --background-image: url();
```
and I went around clicking random shite (selecting channels, opening user profiles, hitting mute/deafen, selecting servers, threads -> create buttons, radio bars and sliders in settings) and have no problem. 

Since I can't replicate a bug, I would like to have a little more information on what exactly doesn't work. If you want, joining the support server and opening a support ticket will likely result in much faster response times since I rarely check gh issues.
