### ISSUE TITLE
[Feature Request] Text background

### ISSUE THREAD

**Issue by efadfa3** [ClearVision/ClearVision-v6#189]
### Did You Search Other Suggestions?

- [X] I have checked if this feature request exists already

### Is your feature request related to a problem?

Yes; the request pertains to certain color roles

### Screenshots and/or description of the feature request.

![image](https://github.com/ClearVision/ClearVision-v6/assets/47500889/ae3f09db-54fc-4115-a777-1d1253123686)
This is my friend posting a monster. The issue seen here is that their name is dark, just like my background, so I cannot see the nickname (and with using role-colored text, I cannot read their messages too)

### Why does the theme need this?

I know I can just change my background, but there will always be some color matching the background or a part of it. I feel like using text background (like a box or even drop shadow kind of deal) would help with that issue. 

### Additional context

I looked around and tried to find a workaround for this by copying code from another themes or trying to use and modify code from [this](https://github.com/ClearVision/ClearVision-v6/issues/61) thread but it didn't work, probably because it's for a completely different issue and because I am really bad at coding.

**Comment by NyxIsBad** [comment]
so here's the thing
case 1: we implement text shadow for all colors
problem: glow on the username is not vanilla design (i know this seems stupid to say when we've already turned discord into a colorful glowing mess but for the most part i'd like not to change discord's design scheme since clearvision has kind of blown up and design changes will affect a ton of people), and there will always be more people complaining about the glow than will have this issue
case 2: we add text glow/change the color for some colors
problem: we can't do this for a range (eg technical limitations means we would have to define this rule for every color), people who like black on black will complain
case 3: we don't add text glow
problem: people like you will have this issue

The thing about case 3 is that it's the least problematic; no matter what background you have (even if it's the default discord background) there will ALWAYS be a range of colors that are difficult to see. I understand that most servers only intend to design role colors for the default experience, but adding text glow universally is just problematic. It's better to handle things on a user by user basis and provide custom css.

That being said, I can help you with custom css. I'd prefer to do it in the support server, where future people can see it + also there's been a lot of reroll nonsense lately, so if you wanna do that, make a thread, and then ping me I'll be happy to help. I do really want to refrain from implementing this in the main theme though, and I hope it's understandable why
