### ISSUE TITLE
Background and Discord Icon are gone

### ISSUE THREAD

**Issue by ToothyDev** [ClearVision/ClearVision-v6#25]
**Describe the bug**
The background (with the deer) and the Discord icon in the top right are gone

**To Reproduce**
1. Open Discord
2. Observe the missing background and icon

**Screenshots**
![image](https://user-images.githubusercontent.com/55001472/101533472-27c48400-3996-11eb-9924-c1037cc1e663.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Discord version: Latest Stable 72915
 - Client/BBD Version: BBD 0.3.5

**Additional context**
The gitlab links all turned invalid, was this abandoned? Would be nice to reupload them somewhere and see a fix!

**Comment by MixusMinimax** [comment]
Same issue here!

The images were hosted on [https://clearvision.gitlab.io/](https://clearvision.gitlab.io/), ([https://clearvision.gitlab.io/images/sapphire.jpg](https://clearvision.gitlab.io/images/sapphire.jpg) for the background) which doesn't seem to exist. GitLab gives me a 404.

That really sucks, because it's my favorite theme...

**Comment by ToothyDev** [comment]
Gitlab page is available again, thus theme is fixed.

**Comment by joker-119** [comment]
Exact same thing just happened again.
